version: 0.2

phases:
  install:
   runtime-version:
      android: 29
   
    commands:
      - echo Install started on `date`
  pre_build:
    commands:
      - npm install
      - echo Pre Build started on `date`
      - wget http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
      - tar -xvf android-sdk_r24.4.1-linux.tgz
      - sudo mv android-sdk-linux /opt/
      - export ANDROID_HOME=/opt/android-sdk-linux
      - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
      - mkdir $ANDROID_HOME/licenses
  build:
    commands:
      - echo Build started on `date`
      - cd android
      - chmod +x gradlew
      - ./gradlew clean
      - ./gradlew assembleRelease -x bundleReleaseJsAssets
  
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
